name: CI Pipeline

on: 
  pull_request:
  push:
    branches:
      - devel
      - stage



jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0

    steps: 
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

      - name: Run tests
        env: 
          CI: true
        run: npm run test

      - name: Build project
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: my-artifact
          path: codebase/rdicidr-0.1.0/build

  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: codebase/rdicidr-0.1.0/terraform

    steps:
      - uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: terraform init
      - run: terraform plan
        if: github.event_name == 'pull_request'
      - run: terraform apply -auto-approve
        if: github.event_name == 'push'

